/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminShellRouteImport } from './routes/admin._shell'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminShellIndexRouteImport } from './routes/admin._shell.index'
import { Route as AdminShellInventoryRouteImport } from './routes/admin._shell.inventory'
import { Route as AdminShellLeadsRouteImport } from './routes/admin._shell.leads'
import { Route as AdminShellMetalRatesRouteImport } from './routes/admin._shell.metal-rates'
import { Route as AdminShellOrdersRouteImport } from './routes/admin._shell.orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellInventoryRoute = AdminShellInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellLeadsRoute = AdminShellLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellMetalRatesRoute = AdminShellMetalRatesRouteImport.update({
  id: '/metal-rates',
  path: '/metal-rates',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellOrdersRoute = AdminShellOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/inventory': typeof AdminShellInventoryRoute
  '/admin/leads': typeof AdminShellLeadsRoute
  '/admin/metal-rates': typeof AdminShellMetalRatesRoute
  '/admin/orders': typeof AdminShellOrdersRoute
  '/admin/': typeof AdminShellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminShellIndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/inventory': typeof AdminShellInventoryRoute
  '/admin/leads': typeof AdminShellLeadsRoute
  '/admin/metal-rates': typeof AdminShellMetalRatesRoute
  '/admin/orders': typeof AdminShellOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/_shell/inventory': typeof AdminShellInventoryRoute
  '/admin/_shell/leads': typeof AdminShellLeadsRoute
  '/admin/_shell/metal-rates': typeof AdminShellMetalRatesRoute
  '/admin/_shell/orders': typeof AdminShellOrdersRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/admin/login'
    | '/order-confirmation/$orderId'
    | '/product/$id'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/metal-rates'
    | '/admin/orders'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/admin/login'
    | '/order-confirmation/$orderId'
    | '/product/$id'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/metal-rates'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/admin/_shell'
    | '/admin/login'
    | '/order-confirmation/$orderId'
    | '/product/$id'
    | '/admin/_shell/inventory'
    | '/admin/_shell/leads'
    | '/admin/_shell/metal-rates'
    | '/admin/_shell/orders'
    | '/admin/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/inventory': {
      id: '/admin/_shell/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminShellInventoryRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/leads': {
      id: '/admin/_shell/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminShellLeadsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/metal-rates': {
      id: '/admin/_shell/metal-rates'
      path: '/metal-rates'
      fullPath: '/admin/metal-rates'
      preLoaderRoute: typeof AdminShellMetalRatesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/orders': {
      id: '/admin/_shell/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminShellOrdersRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellInventoryRoute: typeof AdminShellInventoryRoute
  AdminShellLeadsRoute: typeof AdminShellLeadsRoute
  AdminShellMetalRatesRoute: typeof AdminShellMetalRatesRoute
  AdminShellOrdersRoute: typeof AdminShellOrdersRoute
  AdminShellIndexRoute: typeof AdminShellIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellInventoryRoute: AdminShellInventoryRoute,
  AdminShellLeadsRoute: AdminShellLeadsRoute,
  AdminShellMetalRatesRoute: AdminShellMetalRatesRoute,
  AdminShellOrdersRoute: AdminShellOrdersRoute,
  AdminShellIndexRoute: AdminShellIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

interface AdminRouteChildren {
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
